### ISSUE TITLE
traefik proxy Error

### ISSUE THREAD

**Issue by jujes** [nicokaiser/docker-koken#1]
Hi, someone know how fix when deploy using traefik proxy with ssl?
here my docker-compose.yml

I get: **API Error**

```
API Error

The theme is not able to make contact with your Koken installation. Contact your host to see if they are blocking loopback connections.
```
my docker-compose.yml

```
version: '2'
services:
  pix.jujes.com:
    image: nicokaiser/koken
    container_name: pix.jujes.com
    restart: always
    hostname: pix.jujes.com
    networks:
      - docker_webgateway
    environment:
      - VIRTUAL_HOST=pix.jujes.com
    labels:
      - "traefik.domain=pix.jujes.com"
      - "traefik.enable=true"
      - "traefik.backend=pix.jujes.com"
      - "traefik.frontend.rule=Host:pix.jujes.com, www.pix.jujes.com"
      - "traefik.docker.network=docker_webgateway"
      - "traefik.frontend.entryPoints=http,https"
    links:
      - db.pix.jujes.com

  db.pix.jujes.com:
    image: mysql:latest
    container_name: db.pix.jujes.com
    environment:
      - MYSQL_DATABASE=dbName
      - MYSQL_USER=dbUser
      - MYSQL_PASSWORD=dbPassw
      - MYSQL_ROOT_PASSWORD=dbRootPass
    networks:
      - docker_webgateway
    labels:
      - "traefik.enable=false"

networks:
  docker_webgateway:
    external:
      name: docker_webgateway
```
